#!/bin/bash
# ------------------------------------------------------------------
# [gianc] common_variables
#          Description
# ------------------------------------------------------------------


HEADER="Content-type: application/json"
AUTH="support-247-onduty@jobrapido.com:j0br4p1d0"
BASEURL="https://jobrapido.pagerduty.com/api/v1"
TOKEN="Authorization: Token token=686362e923224b72bf4a30f73b0820c0"

SINCE="--data-urlencode since=2014-02-10T17:00Z"
UNTIL="--data-urlencode until=2014-02-17T10:00Z"
SORT="--data-urlencode sort_by=incident_number:desc"

OFFSET="--data-urlencode offset=0"
LIMIT="--data-urlencode limit=100"

FIELD="--data-urlencode fields=incident_number,created_on,status,assigned_to_user,id,trigger_summary_data"

## local folders and paths
BCK_FOLDER=bck

TMP_GLOBAL_RESULT=$BCK_FOLDER/global.result.json
TMP_SINGLE_RESULT=$BCK_FOLDER/single.result.json

RESULT_INCIDENTS_ID=$BCK_FOLDER/incidentsId.json
RESULT_INCIDENTS_NUMBER=$BCK_FOLDER/incidentsNumber.json

CSV_RESULT=report.csv

## common utilities methods
function logMsg { echo "$1"; }

function writeLine { echo "-------------------------------------"; }

function clean {
	echo
	echo "cleaning.."
	echo

	rm $TMP_GLOBAL_RESULT
	rm $TMP_SINGLE_RESULT

	rm $RESULT_INCIDENTS_ID
	rm $RESULT_INCIDENTS_NUMBER

	rm $CSV_RESULT
}