#!/bin/bash
# ------------------------------------------------------------------
# [gianc] common_variables
#          Description
# ------------------------------------------------------------------

source credentials

HEADER="Content-type: application/json"
AUTH="$USER:$PWD"
BASEURL="https://$CUSTOMER.pagerduty.com/api/v1"
TOKEN="Authorization: Token token=$USER_TOKEN"

SINCE="--data-urlencode since=2014-06-21T04:00Z"
UNTIL="--data-urlencode until=2014-06-21T10:00Z"
SORT="--data-urlencode sort_by=incident_number:desc"

OFFSET="--data-urlencode offset=0"
LIMIT="--data-urlencode limit=100"

FIELD="--data-urlencode fields=incident_number,created_on,status,assigned_to_user,id,trigger_summary_data"

## local folders and paths
BCK_FOLDER=bck

TMP_GLOBAL_RESULT=$BCK_FOLDER/global.result.json
TMP_SINGLE_RESULT=$BCK_FOLDER/single.result.json

RESULT_INCIDENTS_ID=$BCK_FOLDER/incidentsId.json
RESULT_INCIDENTS_NUMBER=$BCK_FOLDER/incidentsNumber.json

AUX_RESULT="aux.result.json"

CSV_RESULT=report.csv

## common utilities methods
function logMsg { echo "$1"; }

function writeLine { echo "-------------------------------------"; }

function clean {
	echo
	echo "cleaning.."
	echo

	rm $TMP_GLOBAL_RESULT
	rm $TMP_SINGLE_RESULT

	rm $RESULT_INCIDENTS_ID
	rm $RESULT_INCIDENTS_NUMBER

	rm $AUX_RESULT

	rm $CSV_RESULT
}
