#!/bin/bash
# ------------------------------------------------------------------
# [gianc] parser
#          Description
# ------------------------------------------------------------------

VERSION=0.1.0
SUBJECT=parser

USAGE="Usage: parser [list|details INCIDENT_ID]"

# --- Options processing -------------------------------------------

if [ $# == 0 ] ; then
    echo $USAGE
    exit 1;
fi


###########################################
# set some variables
source common_variables


function parseAllIncidents {
	echo "try to parse list of incidents.."
	hasMoreIncidents=0
	index=0
	while [ $index -le 200 ] && [ $hasMoreIncidents -eq 0 ]; do
		ITEM=`cat $TMP_GLOBAL_RESULT | ./jq '.incidents['$index'].id'`
		if [ "$ITEM" != '' ] && [ "$ITEM" != 'null' ]; then
			echo "incident num $index id: $ITEM"

		else
			echo "no more incidents"
			hasMoreIncidents=1
		fi
		index=$(( $index + 1 ))
	done
}


function parseSingleIncident {
	echo "try to parse singlo incident.."
	hasMoreLogs=0
	logIndex=0
	while [ $logIndex -le 200 ] && [ $hasMoreLogs -eq 0 ]; do
		ITEM=`cat $TMP_SINGLE_RESULT | ./jq '.log_entries['$logIndex'].type'`
		if [ "$ITEM" != '' ] && [ "$ITEM" != 'null' ]; then
			CREATEDON=`cat $TMP_SINGLE_RESULT | ./jq '.log_entries['$logIndex'].created_at'`
			echo "log num $logIndex type: $ITEM at $CREATEDON"
			
		else
			echo "no more logs"
			hasMoreLogs=1
		fi
		logIndex=$(( $logIndex + 1 ))
	done
}