#!/bin/bash
# ------------------------------------------------------------------
# [gianc] report_builder
#          Description
# ------------------------------------------------------------------

VERSION=0.1.0
SUBJECT=report_builder

USAGE="Usage: report_builder [list|details INCIDENT_ID]"

# --- Options processing -------------------------------------------

if [ $# == 0 ] ; then
    echo $USAGE
    exit 1;
fi


ACTION=$1
SUBACTION=$2

echo "ACTION" $ACTION
echo "SUBACTION" $SUBACTION

###########################################

# set some variables
source common_variables

# include parser
source parser

AUX_RESULT="aux.result.json"

function getAllIncidentsNew {
	writeLine
	echo "getAllIncidents|BEGIN"
	curl -H $HEADER --basic --user $AUTH -X GET -G $SINCE $UNTIL $FIELD $LIMIT $OFFSET $BASEURL/incidents > $AUX_RESULT

	TOTAL=`cat $AUX_RESULT | ./jq '.total'`
	


	echo "getAllIncidents|END"
}


function getAllIncidents {
	writeLine
	echo "getting list of incidents.."
	curl -H $HEADER --basic --user $AUTH -X GET -G $SINCE $UNTIL $FIELD $BASEURL/incidents > $TMP_GLOBAL_RESULT	
	echo "list of incidents response saved in $TMP_GLOBAL_RESULT file"
}

function getSingleIncident {
	writeLine
	echo "getting details for incident with id: $1" 
	curl -H $HEADER --basic --user $AUTH -X GET -G $BASEURL/incidents/$1/log_entries > $TMP_SINGLE_RESULT
	echo "details response for incident with id: $1 saved in $TMP_SINGLE_RESULT file" 
}





if [ "$ACTION" = 'getAll' ]; then
	getAllIncidents
	writeLine
fi


if [ "$ACTION" = 'list' ]; then
	getAllIncidents
	writeLine
	sleep 3
	parseAllIncidents
	writeLine
fi


if [ "$ACTION" = 'details' ] && [ "$SUBACTION" != '' ]; then
	INCIDENTID=$SUBACTION
	getSingleIncident $INCIDENTID
	writeLine
	sleep 3
	parseSingleIncident
fi



if [ "$ACTION" = 'report' ]; then
	#getAllIncidents	
	#writeLine
	#sleep 3
	hasMoreIncidents=0
	index=0
	while [ $index -le 1 ] && [ $hasMoreIncidents -eq 0 ]; do
		INCIDENTID=`cat $TMP_GLOBAL_RESULT | ./jq '.incidents['$index'].id'`
		if [ "$INCIDENTID" != '' ] && [ "$INCIDENTID" != 'null' ]; then
			sleep 1
			echo "trying to get details for incident number $index with id: $INCIDENTID"
			writeLine
			getSingleIncident $INCIDENTID
			sleep 1
			writeLine
			parseSingleIncident
			sleep 1
		else
			echo "no more incidents"
			hasMoreIncidents=1
		fi
		index=$(( $index + 1 ))
	done	
fi

